// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utzvdgbzxkucicydqhkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0enZkZ2J6eGt1Y2ljeWRxaGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzQyMTgsImV4cCI6MjA2NDk1MDIxOH0.M4lUI5083rza7eTc-POrwA-CftQDQ3bmvzKfU_mUoPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);